apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-sl6e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-sl6e
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-sl6e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-sl6e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-sl6e
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-razn-tenant/nodejs-users/simple-nodejs-app-sl6e@sha256:fb3f109f00443bfb4883af93ac0fd90edb30514ec6cdcb42eb211aab3b36485b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
